/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuthKey {
  createdAt: Generated<Timestamp | null>;
  googleRefreshToken: string | null;
  hashedPassword: string | null;
  id: Generated<string>;
  userId: string | null;
}

export interface Bills {
  billNumber: string | null;
  billTitle: string | null;
  billUrl: string;
  committeeAssignment: string | null;
  createdAt: Generated<Timestamp | null>;
  currentStatus: Generated<string | null>;
  currentStatusString: string;
  description: string;
  foodRelated: Generated<boolean | null>;
  id: Generated<string>;
  introducer: string | null;
  nickname: string | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface PendingProposals {
  approvalStatus: Generated<string>;
  billId: string;
  currentStatus: string;
  id: Generated<string>;
  note: string | null;
  proposedAt: Generated<Timestamp>;
  proposedByUserId: string;
  suggestedStatus: string;
  userId: string;
}

export interface SchemaMigrations {
  dirty: boolean;
  version: Int8;
}

export interface ScrapingStats {
  billsScraped: Generated<number | null>;
  createdAt: Generated<Timestamp | null>;
  errorMessage: string | null;
  id: Generated<string>;
  lastScrapeTime: Timestamp;
  success: Generated<boolean | null>;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: Generated<string>;
  sessionToken: string;
  userId: string | null;
}

export interface StatusUpdates {
  billId: string;
  chamber: string;
  date: string;
  id: Generated<string>;
  statustext: string;
}

export interface SupervisorUsers {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  supervisorId: string;
  userId: string;
}

export interface User {
  accountStatus: string;
  authProvider: Generated<string | null>;
  createdAt: Generated<Timestamp | null>;
  email: string;
  googleId: string | null;
  id: Generated<string>;
  profilePictureUrl: string | null;
  requestedAdmin: Generated<boolean>;
  requestedSupervisor: Generated<boolean | null>;
  role: Generated<string>;
  username: string;
}

export interface UserBills {
  adoptedAt: Generated<Timestamp | null>;
  billId: string | null;
  id: Generated<string>;
  userId: string | null;
}

export interface DB {
  authKey: AuthKey;
  bills: Bills;
  pendingProposals: PendingProposals;
  schemaMigrations: SchemaMigrations;
  scrapingStats: ScrapingStats;
  sessions: Sessions;
  statusUpdates: StatusUpdates;
  supervisorUsers: SupervisorUsers;
  user: User;
  userBills: UserBills;
}
