/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuthKey {
  created_at: Generated<Timestamp | null>;
  google_refresh_token: string | null;
  hashed_password: string | null;
  id: Generated<string>;
  user_id: string | null;
}

export interface Bills {
  bill_number: string | null;
  bill_title: string | null;
  bill_url: string;
  committee_assignment: string | null;
  created_at: Generated<Timestamp | null>;
  current_status: Generated<string | null>;
  current_status_string: string;
  description: string;
  food_related: Generated<boolean | null>;
  id: Generated<string>;
  introducer: string | null;
  nickname: string | null;
  updated_at: Generated<Timestamp | null>;
}

export interface PendingProposals {
  approval_status: Generated<string>;
  bill_id: string;
  current_status: string;
  id: Generated<string>;
  note: string | null;
  proposed_at: Generated<Timestamp>;
  proposed_by_user_id: string;
  suggested_status: string;
  user_id: string;
}

export interface SchemaMigrations {
  dirty: boolean;
  version: Int8;
}

export interface ScrapingStats {
  bills_scraped: Generated<number | null>;
  created_at: Generated<Timestamp | null>;
  error_message: string | null;
  id: Generated<string>;
  last_scrape_time: Timestamp;
  success: Generated<boolean | null>;
}

export interface Sessions {
  created_at: Generated<Timestamp | null>;
  expires_at: Timestamp;
  id: Generated<string>;
  session_token: string;
  user_id: string | null;
}

export interface StatusUpdates {
  bill_id: string;
  chamber: string;
  date: string;
  id: Generated<string>;
  statustext: string;
}

export interface User {
  account_status: string;
  auth_provider: Generated<string | null>;
  created_at: Generated<Timestamp | null>;
  email: string;
  google_id: string | null;
  id: Generated<string>;
  profile_picture_url: string | null;
  requested_admin: Generated<boolean>;
  role: Generated<string>;
  username: string;
}

export interface UserBills {
  adopted_at: Generated<Timestamp | null>;
  bill_id: string | null;
  id: Generated<string>;
  user_id: string | null;
}

export interface DB {
  auth_key: AuthKey;
  bills: Bills;
  pending_proposals: PendingProposals;
  schema_migrations: SchemaMigrations;
  scraping_stats: ScrapingStats;
  sessions: Sessions;
  status_updates: StatusUpdates;
  user: User;
  user_bills: UserBills;
}
