---
name: 'deploy'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@dokku-pmf-sandbox.westus2.cloudapp.azure.com:22/bill-tracker'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_SANDBOX_DOKKU }}
          branch: main